lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.NewListView.as_view(), name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    # url(r'^(?P<pk\d+)/$', views.ViewAndAddToList.as_view(), name='view_list'),
]

superlists/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^$', list_views.HomePageView.as_view(), name='home'),
    url(r'^lists/', include(list_urls)),
    path('admin/', admin.site.urls),
]

lists/models.py
from django.db import models
from django.urls import reverse


class List(models.Model):

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):

    def __str__(self):
        return self.text

    text = models.TextField(default='')
    list = models.ForeignKey(List, on_delete=None, default=None)

    class Meta:
        ordering = ('id', )
        unique_together = ('list', 'text')

    def get_absolute_url(self):
        return reverse('view_list', args=[self.list.id])

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You 've already got this in your list"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            })
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

lists/views.py
from django.shortcuts import render, redirect
from lists.forms import ExistingListItemForm, ItemForm
from lists.models import List
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import FormView, CreateView, DetailView


class HomePageView(FormView):
    template_name = 'home.html'
    form_class = ItemForm


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save(for_list=list_)
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})


class NewListView(CreateView):
    template_name = 'home.html'
    form_class = ItemForm

    def form_valid(self, form):
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content=" IE=edge">
    <meta name="viewport" content="widht=device-width, initial-scale=1">
    <title>To-Do lists</title>

    {% load static %}
    <link href="{% static "lists/css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "lists/css/base.css" %} " rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="mt-4 d-flex justify-content-center jumbotron">
        <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            <form method="POST" action="{% block form_action %}{% endblock %}">
                {% csrf_token %}
                {{ form.text }}
                {% if form.errors %}
                <div class="form-group has-error">
                    <span class="help-block">{{ form.text.errors }}</span>
                </div>
                 {% endif %}
            </form>
        </div>
    </div>
        <div class="d-flex justify-content-center ">
                        {% block table %}
                        {% endblock %}
        </div>

</div>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %} {% url 'view_list' list.id %} {% endblock %}

{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
</table>
{% endblock %}